### ISSUE TITLE
Gatsby v3: gatsby-image has been deprecated in favor of gatsby-plugin-image

### ISSUE THREAD

**Issue by mhatvan** [Vagr9K/gatsby-advanced-starter#108]
I will probably bootstrap a new client project with your starter library in the coming weeks and it would be awesome to have Gatsby v3 up and running!

Unfortunately, the npm package is officially marked as deprecated:
https://www.npmjs.com/package/gatsby-image

Here is the migration guide:
https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

**Comment by Vagr9K** [comment]
@mhatvan Thanks for reporting!
