### ISSUE TITLE
Error: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by smashou** [Vagr9K/gatsby-advanced-starter#12]
- Gatsby v1.8.11
- Gatgsby-advanced-starter v1.1.0

When I try to build the last version of gatsby advanced starter with the last version of gatsby I get the following error during the HTML static pages generation:
```
Error: 
    Error: Cannot read property 'pathname' of undefined
    
    - render-page.js:31208 PostTemplate.render
      render-page.js:31208:37
    
    - render-page.js:18952 ReactCompositeComponentWrapp  er._renderValidatedComponentWithoutOwnerOrContext
      render-page.js:18952:31
    
    - render-page.js:18975 ReactCompositeComponentWrapp  er._renderValidatedComponent
      render-page.js:18975:33
    
    - render-page.js:18515 ReactCompositeComponentWrapp  er.performInitialMount
      render-page.js:18515:31
    
    - render-page.js:18411 ReactCompositeComponentWrapp  er.mountComponent
      render-page.js:18411:22
    
    - render-page.js:11323 Object.mountComponent
      render-page.js:11323:36
    
    - render-page.js:17552 ReactDOMComponent.mountChild  ren
      render-page.js:17552:45
    
    - render-page.js:14562 ReactDOMComponent._createCon  tentMarkup
      render-page.js:14562:33
    
    - render-page.js:14429 ReactDOMComponent.mountCompo  nent
      render-page.js:14429:30
    
    - render-page.js:11323 Object.mountComponent
      render-page.js:11323:36
error Command failed with exit code 1.
```
I tried to install a new version from scratch but it's the same error during the build.

**Comment by Vagr9K** [comment]
If you clone the repo, and install the dependencies via `yarn` or `npm install`, do you still get build errors?

**Comment by smashou** [comment]
With your version of Gatsby (v1.4.1) it works well ! But with the last version of gatsby (1.8.11) there is the above error.
I tried the last version of gatsby because of this build problem [issue #1659](https://github.com/gatsbyjs/gatsby/issues/1659).

Do you have any idea about this error ?

**Comment by Vagr9K** [comment]
Well, this starter wasn't upgraded because I am low on time currently.
Changelogs also don't indicate any breaking changes involving `pathname`.

**Comment by Vagr9K** [comment]
Seems like an upstream bug, but a workaround will do it for now.

**Comment by Vagr9K** [comment]
@smashou can you confirm that the new version works?
