### ISSUE TITLE
Use Starter without TypeScript/Remove TypeScript

### ISSUE THREAD

**Issue by canadianeagle** [Vagr9K/gatsby-advanced-starter#123]
Hello @Vagr9K ,

First of all, thanks for the starter - literally has everything I need to launch the blog section of my website.

The problem is, I don't want to use TypeScript. 

Is there a version without TypeScript? After cloning the repo, everything appears to be typed (as the repo indicates). But before trying to manually convert to good ol' JS, I thought I should ask first.

Also, is there any functionality that will be lost by switching from TypeScript?

Thanks again,

T

**Comment by Vagr9K** [comment]
Hello @canadianeagle!

Yes, you can use the repo without TypeScript and you won't lose any functionality.

Simply put your code into `.js` and `.jsx` files.

Note that most of the TS code in this repo comes from `themes` and their tests which you don't need to modify directly (see [Receiving Upstream Updates](https://github.com/Vagr9K/gatsby-advanced-starter#receiving-upstream-updates) for details).

If you run into any issues please let me know.
I'll make sure to add extra documentation regarding the subject in the future!

**Comment by canadianeagle** [comment]
Thanks so much for the quick response @Vagr9K  Cheers :)
