### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by antranapp** [Vagr9K/gatsby-advanced-starter#125]
I am trying to install the theme using `gatsby` cli
```
gatsby new YourProjectName https://github.com/Vagr9K/gatsby-advanced-starter
```

but it fails to run `npm install`

```
➜  web git:(main) ✗ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-advanced@3.2.2
npm ERR! Found: cypress@8.2.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^8.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^3 || ^4 || ^5 || ^6" from cypress-axe@0.12.2
npm ERR! node_modules/cypress-axe
npm ERR!   dev cypress-axe@"^0.12.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

npm ERR! A complete log of this run can be found in:

```

**Comment by Vagr9K** [comment]
It looks like NPM fails to resolve the dependencies.

To be honest the project primarily supports Yarn and relies on its workspace features. I'll add a note regarding this in its documentation in the future.

Can you try using yarn as your Gatsby package manager as outlined in the [gatsby cli documentation](https://www.gatsbyjs.com/docs/glossary/yarn/)?

Alternatively you can clone/fork the project and run `yarn` in the root directory. That's effectively the same as installing it via `gatsby new`.

**Comment by antranapp** [comment]
Yep, it works with Yarn
