### ISSUE TITLE
Instructions not working (gatsby serve not working)

### ISSUE THREAD

**Issue by christiankopac** [Vagr9K/gatsby-advanced-starter#13]
## Getting Started

Install this starter (assuming Gatsby is installed) by running from your CLI:
```zsh
gatsby new YourProjectName https://github.com/Vagr9K/gatsby-advanced-starter
npm run serve
```
Or you can fork the project, make your changes there and merge new features when needed.

Alternatively:
```zsh
git clone https://github.com/Vagr9K/gatsby-advanced-starter YourProjectName # Clone the project
cd YourProjectname
rm -rf .git # So you can have your own changes stored in VCS.
npm install # or yarn
npm run serve
```
---

Checking the `package.json` I see the `npm run serve` command runs `gatsby serve`. 

Taken from the Gatsby documentation: 
`gatsby develop` — Gatsby will start a hot-reloading development environment accessible at localhost:8000
`gatsby build` — Gatsby will perform an optimized production build for your site generating static HTML and per-route JavaScript code bundles.
`gatsby serve` — Gatsby starts a local HTML server for testing your built site.

Using `gatsby serve` "serves" the site, but it doesn't show anything (nor the index, nor the about page). Index shows empty page, about says 404. To me seems like the queries are not working when serving instead of hot reloading. On the other hand, when running `gatsby develop` I can see the default gatsby-advanced-starter page without any problems.

---
Can I make a pull request for the small fixes at the `README.md` so that other users at least have a working copy when following the instrucitons? Any other ideas how to debug and fix this?

Fixed getting started instructions (working example):

## Getting Started

Install this starter (assuming Gatsby is installed) by running from your CLI:
```zsh
gatsby new YourProjectName https://github.com/Vagr9K/gatsby-advanced-starter
npm install # or yarn install
npm run develop # or gatsby develop
```
Or you can fork the project, make your changes there and merge new features when needed.

Alternatively:
```zsh
git clone https://github.com/Vagr9K/gatsby-advanced-starter YourProjectName # Clone the project
cd YourProjectname
rm -rf .git # So you can have your own changes stored in VCS.
npm install # or yarn install
npm run develop # or gatsby develop
```

**Comment by Vagr9K** [comment]
Hmm. Back in the day I had `serve` aliased to `develop`, but decided to change it for consistency.

If you feel like opening a pull request, go for it. I'll merge it :)

**Comment by christiankopac** [comment]
Thanks!
