### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by pedrocatre** [Vagr9K/gatsby-advanced-starter#157]
When running `gatsby new YourProjectName https://github.com/Vagr9K/gatsby-advanced-starter` I get:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-advanced@3.2.2
npm ERR! Found: cypress@8.4.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^8.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^3 || ^4 || ^5 || ^6" from cypress-axe@0.12.2
npm ERR! node_modules/cypress-axe
npm ERR!   dev cypress-axe@"^0.12.2" from the root project
```

I can work around that by doing

`npm config set legacy-peer-deps true` as explained here [https://stackoverflow.com/a/65733374/3094399](https://stackoverflow.com/a/65733374/3094399)

but then I get:

```
success Created starter directory layout
info Installing packages...

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:

 ERROR

Command failed with exit code 1: npm install
```

Any idea how I can move forward?

**Comment by Vagr9K** [comment]
npm fails due to the project using Yarn specific `workspace:*` functionality.

Can you try using yarn as your Gatsby package manager as outlined in the Gatsby CLI documentation?

Alternatively you can clone/fork the project and run yarn in the root directory. That's effectively the same as installing it via `gatsby new`.

**Comment by Vagr9K** [comment]
With the latest update you should be able to use npm without any issues.

`gatsby new` will work out of the box too.

**Comment by pedrocatre** [comment]
Thank you, from the README I see the instructions are right.
If I run the gatsby command the next command it suggested didn't work for me. But with yarn and you suggested it works.

Thank you :)
