### ISSUE TITLE
Mention minimum version of Node.js required in the README

### ISSUE THREAD

**Issue by dhruvmisra** [Vagr9K/gatsby-advanced-starter#164]
Hey there!

I was trying to run the project locally (`yarn develop`) but for some reason none of the post pages were showing up on the second run (all were throwing 404). I checked the console to realise that I had the following error:

```bash
"gatsby-theme-advanced" threw an error while running the createPages lifecycle:

fs_1.default.rmSync is not a function

   96 |
   97 |   // Initialize feed metadata
>  98 |   initFeedMeta();
      |               ^
   99 |
  100 |   // Get full post listing
  101 |   const fullListing = await getIndexListing(graphql);

File: themes/advanced/gatsby/gatsby-node.ts:98:15
```

After spending some time debugging this, I found that `fs.rmSync()` (used by initFeedMeta() method) is not supported in Node.js v12 which I was using at the time. **Switching to Node.js v14 fixed the issue**.

`fs.rmSync()` was added in Node.js v14.14.0 ([Check here](https://nodejs.org/api/fs.html#fs_fs_rmsync_path_options)). As `gatsby-theme-advanced` is dependent on this function, I think it would be better to mention this in the README of the project. Would save some time of debugging for developers.

And yes, thanks for this great project! :)

**Comment by Vagr9K** [comment]
Hey!

Thanks for reporting this.

I was considering adding a section with minimal requirements, but since Gatsby V4 is right around the corner and will require NodeJS v14.15.

By the end of October GatsbyJS will be warning about incompatible versions by itself, so this is a non-issue for the starter at this point.
