### ISSUE TITLE
Support for sites without a `pathPrefix`

### ISSUE THREAD

**Issue by umstek** [Vagr9K/gatsby-advanced-starter#20]
The boilerplate code doesn't allow an empty `pathPrefix` in `data/siteConfig.js` but allows a `/` which will be regarded as `` (empty) somewhere and, there are also some code which will convert `` (empty) `pathPrefix` to a `/`. 
These incompatibilities lead to URLs like `https://org.github.io//test-url` (_note the double slash_) in SEO and social share links.

**Comment by mikecousins** [comment]
Why was this closed? It seems to break the Disqus integration for me. When I use an empty string it breaks the build and when I use a slash it breaks Disqus.

**Comment by Songkeys** [comment]
@Vagr9K 
When run `build`, it throws 
```
ValidationError: child "pathPrefix" fails because ["pathPrefix" is not allowed to be empty]
```
