### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by doakheggeness** [Vagr9K/gatsby-advanced-starter#28]
I am learning Gatsby, so I decided to try this. I got two errors running 'npm run develop' on localhost. I edited siteConfig.js to siteUrl: "http://localhost:8000"

1) Plugin gatsby-transformer-remark returned an error
2)Error compiling site's Graphq; queries.....Unknown field 'timeToRead on type 'MarkdownRemark.

Anything I can do. This is the second gatsby git I have tried with no luck.

**Comment by Vagr9K** [comment]
Sorry for responding 2 weeks later. Didn't have much time to dedicate to OSS.

You have some kind of a dependency issue by the looks of it.

Try installing via NPM/yarn scripts like this:

```
git clone https://github.com/Vagr9K/gatsby-advanced-starter YourProjectName # Clone the project
cd YourProjectname
rm -rf .git # So you can have your own changes stored in VCS.
npm install # or yarn install
npm run develop # or gatsby develop
```

Also, keep in eye on package manager/build warnings.

**Comment by Vagr9K** [comment]
Closing due to lack of details and inactivity.
