### ISSUE TITLE
Mysterious dependencies

### ISSUE THREAD

**Issue by popwebz** [Vagr9K/gatsby-advanced-starter#29]
This project looks like a great starting point for gatsby sites. Though I do have a few questions:

1. Why is ReactDOM listed on package.json? I do not see it called anywhere on this project or the casper project.
2. It looks like React 16 is used. Is there a specific reason for this and why is gatsby-plugin-next not used?
3. stylefmt is installed but doesn't stylelint package do everything that this plugin handles already?

Also, what is the purpose of lodash? I see a lot of gatsby projects but I'm not sure what it does with respect to gatsby (just now discovering gatsbyjs)

Thank you.

**Comment by Vagr9K** [comment]
It seems like React/ReactDOM were added to the package list by a mistake while I was upgrading dependencies in yarn.

Stylelint only lints styles. If you want formatting in your editor/tools you need stylefmt.

lodash is used in gatsby-node.js

**Comment by popwebz** [comment]
Thank you for these pointers. I am coming from Hugo and the learning curve is a bit overwhelming with Gatsby but it looks like it will be worth it.
