### ISSUE TITLE
SEO and gatsby-image not building

### ISSUE THREAD

**Issue by thomasheimstad** [Vagr9K/gatsby-advanced-starter#30]
The SEO-component works great for all post meta-info except images.

I use gatsby-image to fetch different sizes for the hero-images of each post like so:

```
thumbnail {
          childImageSharp {
            sizes(maxWidth: 1920) {
              ...GatsbyImageSharpSizes
            }
          }
        }
```

When using the SEO-component, I'm trying to access the src of the hero images (named "thumbnail" in the post frontmatter) like this:

```
if (postSEO) {
      const postMeta = postNode.frontmatter;
      ...
      image = postMeta.thumbnail.childImageSharp.sizes
    }
```
but the Netlify-build fails with "can't read childImageSharp of undefined" or something similar. It seems that it can't process the image in this way. The hero image gets it correct though, so it's not an issue of the image itself.

Ive also tried:
`image = postMeta.thumbnail.childImageSharp.sizes.src`
to no avail.

Any clues?

**Comment by Vagr9K** [comment]
> but the Netlify-build fails

First, does it build locally?

> can't read childImageSharp of undefined

Open the GraphQL debugger for gatsby (localhost:3000/__graphql) and make sure the nodes you are trying to access actually do exist.

**Comment by Vagr9K** [comment]
PR https://github.com/Vagr9K/gatsby-advanced-starter/pull/33 adds Netlify deploy configuration and `gatsby-image` configuration to fetch data from `/static/` automatically.

From here you should be able to add your client side code for querying and displaying optimized images.
