### ISSUE TITLE
Footer component possible bug

### ISSUE THREAD

**Issue by irvingv8** [Vagr9K/gatsby-advanced-starter#4]
ATM the footer component is importing config from data/SiteConfig. However this is not being used as the component is intended to work with a expected config passed in as props.

I'd recommend one of this: 
- not importing config in the component (as it's not being used)
- use the imported config and drop the prop
- check wether a prop was given and fallback to the imported config

If you would like me to submit a PR fixing this, just let me know which option you feel should be implemented

**Comment by Vagr9K** [comment]
Thanks for opening the issue!

> not importing config in the component (as it's not being used)
It's actually being used for `<UserLinks config={config} labeled />`.

Since a future refactoring is planned, I'd go for using `this.props.config` instead of `config`.

PR are always welcome :)

**Comment by irvingv8** [comment]
> It's actually being used for <UserLinks config={config} labeled />.

oh! You are totally right! I overlooked that bit.
