### ISSUE TITLE
Reduce Layout cyclomatic complex

### ISSUE THREAD

**Issue by Scot3004** [Vagr9K/gatsby-advanced-starter#42]
the method getLocalTitle from layout should be refactored
it's cyclomatic complex is high because it have an if which could be replaced by a new prop sent from each part where it's used and remove this required conditional that was required for gatsby v1
this applies only for v2 branch

**Comment by Vagr9K** [comment]
Fixed in https://github.com/Vagr9K/gatsby-advanced-starter/commit/d6b76a185f7e1095a2181d5f203b4f87f0f576cd.
