### ISSUE TITLE
How to disable bundling in developement mode

### ISSUE THREAD

**Issue by shashankKeshava** [Vagr9K/gatsby-advanced-starter#45]
Hi

How do I disable bundling in development mode? Currently, all the code is bundled and I'm facing hard to debug.

![image](https://user-images.githubusercontent.com/15323807/45945918-c3af8280-c00c-11e8-9366-a8e0ae888715.png)

**Comment by shashankKeshava** [comment]
Hi @Vagr9K 

I'm trying to debug in development mode but the code is completely bundled and is in vanilla JS. Is it possible to debug without converting ES7 to vanilla JS ?

**Comment by Vagr9K** [comment]
> possible to debug without converting ES7 to vanilla JS ?

As far as I know it's not, since the code can't run without being transpiled into ES5.

That being said, the Sources tab of the Dev Tools contains original source code (based on sourcemaps). You should be able to set breakpoints/etc. there without having to view transpiled code.
