### ISSUE TITLE
how can separate content on multiple pages

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Vagr9K/gatsby-advanced-starter#50]
Hey I want to keep 3 jsx pages and want to distribute content .md on those three pages. So for example 

If I have my entire blog has 3 separate pages ie. maths, ai, computerscience

I want to sort of want three directories in content folder ie. maths, ai, computerscience and based on content kept on that it be render on those jsx pages. Is this possible? 

If yes how?

**Comment by Vagr9K** [comment]
First of all, apologies for the late answer!

First of all take a look at: https://www.gatsbyjs.org/docs/adding-markdown-pages/.

Based on this knowledge you'll need to modify `gatsby-node.js` and add additional page components to `src/templates`.

In the starter, you can use the implementation of `post.jsx`, `category.jsx` and `tag.jsx` under `src/templates` as a reference.
