### ISSUE TITLE
Question: what is the correlation between frontmatter.category and category_id

### ISSUE THREAD

**Issue by curlywater** [Vagr9K/gatsby-advanced-starter#54]
We can set the post's category by frontmatter, but can not set the category_id used in Disqus.
What is the correlation between frontmatter.category and category_id?

**Comment by Vagr9K** [comment]
You should be able to set `category_id` in the frontmatter same way as the `category`. 
If not set it falls back to `postDefaultCategoryID` that's set in `SiteConfig.js`

This allows people to set internal categories that will be displayed in their blogs and possibly a different category for Disqus.
