### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by Ynewtime** [Vagr9K/gatsby-advanced-starter#58]
Thanks for the convenience this starter brings.

Well, let's make it simple.
 
Firstly, this starter comes with an issue of [@hot-reloader warning](https://github.com/gatsbyjs/gatsby/issues/11934)(check the browser console after rendered), I fixed it following [this thread](https://github.com/gatsbyjs/gatsby/issues/11934#issuecomment-469046186).

```
React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.
```

Secondly, when a markdown file has a front matter `cover` field set with an url string, like below, the html head meta content goes wrong, it is caused by [this line](https://github.com/Vagr9K/gatsby-advanced-starter/blob/b9d70edabdad13a4d7c8fa21da8209d69e0dbcb1/src/components/SEO/SEO.jsx#L27) in `src/components/SEO/SEO.jsx`, I fixed it by checking if the cover field was an url string first:

 ```markdown
---
#markdown front matter
title: "The Fallen Time"
cover: "https://unsplash.it/400/300/?random?TheFallenTime"
---
```

```js
//the way to fix it
if (!image.match(`(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]`)) 
image = urljoin(config.siteUrl, config.pathPrefix, image);
```

**Comment by koolamusic** [comment]
@Ynewtime  what file are you expected to add this line 
```
if (!image.match(`(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]`)) 
image = urljoin(config.siteUrl, config.pathPrefix, image);
```

**Comment by Ynewtime** [comment]
@koolamusic src/components/SEO/SEO.jsx

**Comment by Vagr9K** [comment]
I'll ignore the warning for now since it's harmless and should be fixed by the upstream Gatsby.
The issues with incorrect URI  generation is fixed now.

Thank you for reporting the issue and providing a fix. :)

**Comment by jonmccon** [comment]
I'm actually not using the `cover` attribute in my post setup and this new line is causing the error: 
`TypeError: Cannot read property 'match' of undefined`
 Taking it out drops me on a single post instead of my index page. Not sure why, are there required attributes to a post?

**Comment by jonmccon** [comment]
I rescind my statement. Had a `#` in a title and it broke from this snippet trying to make sense of it. All good. Thanks for all the work on this!
