### ISSUE TITLE
Add a key to the posts in PostListing.jsx

### ISSUE THREAD

**Issue by irvingv8** [Vagr9K/gatsby-advanced-starter#6]
Adding a key to the posts will get rid of the warning in React, ATM I'm using the posts title as a key. might be submitting a PR later today (unless you have already fixed this in the next release?).

**Comment by Vagr9K** [comment]
I forgot to backport the fix from the Material Starter.
Thanks for reporting!

**Comment by irvingv8** [comment]
No worries, I have an unrelated doubt: Is there any reason why you didn't add Sass support out of the box ?

**Comment by Vagr9K** [comment]
Decided to make this starter as unopinionated as possible. Especially since adding Sass support is really easy.

**Comment by Vagr9K** [comment]
On an unrelated note CSS-in-JS vs CSS/SASS is a holy war at this point.
The phrase "I prefer `whatever-x`" gets you into heated arguments with 0 facts in seconds.
