### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by StephanWeinhold** [Vagr9K/gatsby-advanced-starter#61]
This is not exactly an issue, I know. Has anyone achieved to have a pagination with an advanced-starter-blog? I've tried several plugins, I've had a look at #15. But I always stumble over createPage(). Has anyone a working solution?

**Comment by K-Sato1995** [comment]
Here is a great instruction for this.

https://nickymeuleman.netlify.com/blog/gatsby-pagination
