### ISSUE TITLE
Having trouble using Disqus

### ISSUE THREAD

**Issue by yoonoh930** [Vagr9K/gatsby-advanced-starter#66]
I am trying to activate Disqus comments on my blog but it's not working.

So far I've put the disqusShortName on siteConfig. I've put my domain on trusted site on Disqus site. But still it's not showing on my blog.

The blog address is [https://yoons.blog](https://yoons.blog) and the source code is here: [https://github.com/yoonoh930/gatsby-blog](https://github.com/yoonoh930/gatsby-blog)

**Comment by Vagr9K** [comment]
Unfortunately I don't have any tips for you here since I can't replicate it with my credentials.

Double check if your shortname, domain whitelist are fine I suppose.
Check if your browser blocks discuss via third party extensions (adblockers, privacy enhancers) too.

**Comment by yoonoh930** [comment]
Just to make it simple, I made a new netlify site with just SiteConfig.js file changed from the data file.

Source [code](https://github.com/yoonoh930/gatsby-test-blog-disqus/blob/master/data/SiteConfig.js)
[Site](https://happy-murdock-211b60.netlify.com/)

As you can see from the code, I've only changed siteUrl and disqusShortname accordingly. Everything else is intact.
From disqus site, I've listed 
happy-murdock-211b60.netlify.com
netlify.com
as trusted domains.

Also changed Website Url on the disqus setting to 
https://happy-murdock-211b60.netlify.com

Still comments are now showing :/

**Comment by yoonoh930** [comment]
Installed and implemented disqus using `gatsby-plugin-disqus`. It works now!

**Comment by pluralsigher** [comment]
Im having issues with Disqus. Could you share how you got it to work if you see this @yoonoh930? 

I have tried to: 
- Setup the disqusshortname in config.website in the root gatsby-config.js
- Then remove public/ and cache/ then build on production - not working. 

- Then I tried to install the plugin with `yarn add gatsby-plugin-disqus -W` (although it shouldnt be needed) and removed the resolve part for the plugin inside the `themes/advanced/gatsby/gatsby-config.ts` and then put this the root config: 
```
    {
      resolve: "gatsby-plugin-disqus",
      options: {
        shortname: "www-mydisqus-com",
      },
    },
```
- Then clean public and cache and build again in production - still not loading. 
- I dont see any errors when building or errors in the console of chrome.

Im running out of ideas on what to test next...

Any advice on how to troubleshoot?

**Comment by pluralsigher** [comment]
Tried to remove this code in `themes/advanced/src/components/Disqus/index.tsx`
```
  // Do not render if no shortname was provided
  // if (!config.website.disqusShortname) {
  //   return null;
  // }
```

Then I removed public, cache and built on production and still not seeing any Disqus section in the browser. 
My account name is correct, currently I have the plugin configured as above, like this in root `gatsby-config.js:` 

```
    {
      resolve: "gatsby-plugin-disqus",
      options: {
        shortname: "www-mydisqus-com",
      },
    },
```

If I inspect the page and look below the Share section, I see no sign of disqus there.

**Comment by elbuendiscipulo** [comment]
Thank you for pointing me in the right direction, @Vagr9K.

Is it possible to pass the `website` in the option parameter to the Amaranth theme? 

Like this in `gatsby-config.js` in root: 
<img width="492" alt="Screen Shot 2021-12-22 at 7 28 44" src="https://user-images.githubusercontent.com/94419591/147112769-05e6316b-7c69-4e42-b6e3-c12959aecaad.png">

The `gatsby-config.js` in the amaranth theme is unchanged and looks like this: 
<img width="405" alt="Screen Shot 2021-12-22 at 9 24 33" src="https://user-images.githubusercontent.com/94419591/147115595-7d328c5b-b489-4c8f-87b5-4d777c9867f7.png">

I was able to shadow the index.tsx inside Article and import the Disqus plugin 👍 , now Disqus just cant find the shortname.
<details>
<img width="1318" alt="Screen Shot 2021-12-22 at 8 26 09" src="https://user-images.githubusercontent.com/94419591/147113049-5017ce09-3283-494c-9209-38d487f6fff4.png">
</details>

**Comment by Vagr9K** [comment]
@elbuendiscipulo Yes. It will be forwarded to `gatsby-theme-advanced` for usage with Disqus.

**Comment by elbuendiscipulo** [comment]
I found the error! The shortname setting worked as you said. 
But the `div` with id `#disqus_thread` doesnt have any styling, the div is displayed but with width 1px.

I got it to display correctly by applying the style from `examples/advanced-demo/src/components/Article/styles.css`

```
#disqus_thread {
  width: 100%;
  max-width: 760px;
}
```
<img width="430" alt="Screen Shot 2021-12-23 at 10 44 24" src="https://user-images.githubusercontent.com/94419591/147269446-374779f9-2734-4437-8c65-744c1d100da9.png">

Code:
<details>

```
import React from "react";
import styled from "styled-components";

import Disqus from "../../../../themes/advanced/src/components/Disqus";
import * as Types from "../../../../themes/advanced/src/types";

import Intro from "../../../../themes/amaranth/src/components/Article/Intro";
import Render from "../../../../themes/amaranth/src/components/Article/Render";
import Share from "../../../../themes/amaranth/src/components/Article/Share";

import "./styles.css";

const Wrapper = styled.main`
  width: 100%;

  display: grid;
  grid-gap: 24px;
  justify-items: center;
`;

type ArticleProps = {
  post: Types.Post;
};

const Article = ({ post }: ArticleProps): JSX.Element => (
  <Wrapper>
    <Intro post={post} />
    <Render post={post} />
    <Share post={post} />
    <Disqus post={post} />
  </Wrapper>
);

export default Article;
```

</details>
