### ISSUE TITLE
Image sharp not generated on frontamatter cover image

### ISSUE THREAD

**Issue by pul87** [Vagr9K/gatsby-advanced-starter#69]
I'm trying to modify the post template adding the cover image.
Based on the gatsby-config.js I should find a **childImageSharp** field in the **frontmatter** of the post but I just find the cover field.
Am I missing something?

**Comment by obedparla** [comment]
I'm having the exact same issue. I installed the package and the only changes I've done so far is adding my own posts and images. No changes to config or anything else.

I spent a while trying to figure it out to no success.

**Comment by obedparla** [comment]
I'm not sure what I changed, but now it works flawlessly. I'm pretty sure I tried having all my images with relative paths, but after I re-imported my markdowns it worked (with images having relative paths).
