### ISSUE TITLE
Add better support for gatsby-plugin-sharp.

### ISSUE THREAD

**Issue by Vagr9K** [Vagr9K/gatsby-advanced-starter#7]

**Comment by irvingv8** [comment]
Is this related to the issue I was talking with you about using the plugin to display cover images (set in frontmatter, instead of referencing external images) in the post listing? 

Something among the lines of this:

![image](https://user-images.githubusercontent.com/13772377/29246681-139ba838-7fd0-11e7-80a5-53eb5a159253.png)

**Comment by Vagr9K** [comment]
It is related but not limited to.
I want to add some general mechanisms to generate responsive images and embed them into HTML.

Unfortunately, no time to do that.

**Comment by arcdev1** [comment]
> using the plugin to display cover images (set in frontmatter, instead of referencing external images) in the post listing?

This functionality is already available with gatsby-image. 
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image

Steps to enable:

1. Install dependencies
```
npm install gatsby-image --save
npm install gatsby-transformer-sharp --save
```

2. Add plugin to `gatsby-config.js`
```javascript
plugins: ['gatsby-transformer-sharp']
```

3. Create an `images` folder under `sample-posts`
```
sample-posts
 /images
```

4. Add some images to the new images folder

5. Modify the `cover` property in the frontmatter of all blog posts to point to a local image
```
cover: "../images/some-image.jpg"
```

6. Modify the queries in `pages/index.jsx` and `templates/post.jsx` to include the `childImageSgarp` node
```
cover
  {
    childImageSharp{
     sizes(maxWidth: 720, maxHeight: 400) {
        ...GatsbyImageSharpSizes
      }
    }
  }
```

7. Import `gatsby-image` in `templates/post.jsx`
```javascript
import Img from 'gatsby-image'
```

8. Add an `Img` element to `templates/post.jsx`
```html
<Img sizes={post.cover.childImageSharp.sizes} />
```

You can found out more about the options for childImageSharp at:
https://image-processing.gatsbyjs.org

Hope that helps!

**Comment by Vagr9K** [comment]
Fixed in https://github.com/Vagr9K/gatsby-advanced-starter/pull/33.
