### ISSUE TITLE
warn Plugin `gatsby-source-filesystem` tried to define the GraphQL type `File`

### ISSUE THREAD

**Issue by janetrimmer** [Vagr9K/gatsby-advanced-starter#71]
I have just cloned gatsby-advanced-starter and on running **gatsby develop**, I get the above warning. The site displays ok, though. I tried googling but that brought up nothing.

**Comment by Vagr9K** [comment]
I can't reproduce the issue on my end.
Probably a package misbehaving so just try nuking `node_modules` and reinstalling them.

I'll apply a version bump to all dependencies on the next release too.
