### ISSUE TITLE
Fix SEO Post Schema

### ISSUE THREAD

**Issue by mtoqeer** [Vagr9K/gatsby-advanced-starter#74]
Can you please check BlogPosting Schema. The author is missing, published date and updated date is also missing.

**Comment by mtoqeer** [comment]
[
![image](https://user-images.githubusercontent.com/31422464/74119248-7d969700-4be0-11ea-9775-6e001dc68ee8.png)
](url)

**Comment by Vagr9K** [comment]
Thanks for opening the issue!

This is now fixed in the latest version.
