### ISSUE TITLE
Unable to determine what sets the landing/index page

### ISSUE THREAD

**Issue by aidalgol** [Vagr9K/gatsby-advanced-starter#77]
I have successfully created a basic, non-blog site with a few static pages with an earlier version of this starter, but in the current version, I cannot figure out what sets the default landing page (when the user navigates to `/`).  I can see it's being set to the post-listings page, and I can locate the component for this page, but I only see this component referenced in `gatsby-node.js` in a chunk of code commented simply `// Paging`.

Could you please add an explanation of this mechanism to the README?

**Comment by Vagr9K** [comment]
Hey!

The latest update has re-added the old way of handling landing pages without paging.
You can now apply your changes to `templates/landing.jsx` and set `postsPerPage: 0` if you want to upgrade without much hassle.
