### ISSUE TITLE
Migrate from gatsby-plugin-google-analytics to gatsby-plugin-gtag

### ISSUE THREAD

**Issue by dakshshah96** [Vagr9K/gatsby-advanced-starter#80]
Google recommends using `gtag.js` instead of `analytics.js`. They also have a [migration guide](https://developers.google.com/analytics/devguides/collection/gtagjs/migration) in place.

Do you think it is a good idea to update this starter to use [gatsby-plugin-gtag](https://www.gatsbyjs.org/packages/gatsby-plugin-gtag/) instead of [gatsby-plugin-google-analytics](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/)?

I'll be happy to help out if you think this is a good idea!

**Comment by Vagr9K** [comment]
As of right now both versions are widely used (and neither are deprecated).

`gatsby-plugin-google-analytics` is maintained by the gatsby team, meaning that it will be far more reliable and produce less compatibility issues with the future versions. This makes it a better choice for a general purpose starter.

That being said, starter users are free to utilize `gatsby-plugin-gtag` if they prefer to do so.
