### ISSUE TITLE
JSconfig.json: ../agent-base/dist/src/index not found

### ISSUE THREAD

**Issue by GuillouTran** [Vagr9K/gatsby-advanced-starter#88]
Even though build is compiled and develop mode running just fine! Most major code IDE have a warning on JSconfig.json file about the above error. Logs:

```
{
	"resource": "/home/guilloutran/guilloutran.com/jsconfig.json",
	"owner": "typescript",
	"severity": 8,
	"message": "File '/home/guilloutran/guilloutran.com/node_modules/agent-base/dist/src/index' not found.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
```
I have tried to play around with the agent-base dependencies but it doesn't seem to work! Please advice

**Comment by Vagr9K** [comment]
I'm unable to replicate using VSCode.

Which IDE are you using?

**Comment by Vagr9K** [comment]
The October update will fix this by removing the redundant file.

Thanks for the report!

**Comment by GuillouTran** [comment]
Welcome
